---
- name: install packeges
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ short_packeges }}"

- name: install pip modules
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items: "{{ short_pip_modules }}"
